version: '3'
services:
  default:
    build: 
      context: rpmMake/resources/lazyDir
      dockerfile: centos-7.Dockerfile
      args:
        uid: "${_UID:-1000}"
        gid: "${_GID:-1000}"
    volumes:
      - .:/var/tmp/pkgmake
    working_dir: /var/tmp/pkgmake
    stdin_open: true
    tty: true
    hostname: build.local
    container_name: build.local
    command: bash
    networks:
      - bridge

networks:
  bridge:
    external: true
